### ISSUE TITLE
Rounding error with might

### ISSUE THREAD

**Issue by Zheneq** [Zheneq/hc#30]
Mighted Fetter deals 12 damage instead of 13

**Comment by sbvw7** [comment]
it's correct. like mighted dmg of 50 would be 62.
the number after decimal separator will be ignored directly.

**Comment by Zheneq** [comment]
Sensei's laser primary deals 32 instead of 33 with might

**Comment by Zheneq** [comment]
Fixed in df126be31aefe9ecfa0407a679291f3293516eba
