### ISSUE TITLE
ClaymoreCharge path displayed in decision does not match resolution

### ISSUE THREAD

**Issue by readmaniak** [Zheneq/hc#32]
Oceanus-3 server, build 0.7.1.1 beta. Game 2023_02_05__09_36_24. Decision phase shown garrison getting damaged

**Comment by Zheneq** [comment]
Probably related to other dash issues caused by lancers' positions not updating properly.

**Comment by Zheneq** [comment]
fixed in https://github.com/Zheneq/hc/releases/tag/0.7.5
