### ISSUE TITLE
SpaceMarine Passively gains more energy after using an ability

### ISSUE THREAD

**Issue by Addalyn** [Zheneq/hc#34]
Garrison starts of with 5 energy he gains passively like normal
But as soon as he uses his punch he gains then 6 energy passively  , next turn he gains 7 passively and it stacks up at one point i even saw 12 passif energy gain

Not sure if its cause of punch only or other abilities to

**Comment by Zheneq** [comment]
It's his passive

> Increases energy regeneration by 1 whenever you damage an enemy. Fades if you don't deal damage. Stacks 2 times.

Not sure if the effect wears off though.

![изображение](https://user-images.githubusercontent.com/6827970/218103851-139012eb-3a3f-44eb-a884-a47dff258c7f.png)

**Comment by Zheneq** [comment]
Disabled the passive -- I haven't found anything like it in old footage

Fixed in 054c9f1526d138fd0448127465dca22a8d76aa73
