### ISSUE TITLE
Lancers do not lose might upon death

### ISSUE THREAD

**Issue by Addalyn** [Zheneq/hc#41]
might should no longer apply when player dies on movement fase and fase after that (traps/stickys etc)

**Comment by Addalyn** [comment]
![image](https://user-images.githubusercontent.com/622983/219973211-3a0acf02-74b7-46b3-ab95-b6c36f2e58cd.png)

**Comment by Zheneq** [comment]
Doesn't look like a bug. Any proofs that it's not how it's supposed to be?

**Comment by Zheneq** [comment]
Probably we should clear all actor effects at the end of the turn.

**Comment by Zheneq** [comment]
Fixed in 837bd43f269dcdc0f2309c6f5bf94d3b442b0a4a
