### ISSUE TITLE
celestes can't grab the same powerup

### ISSUE THREAD

**Issue by AuricImpulse** [Zheneq/hc#57]
Hyperion-1 - 0.7.4 - 2023_11_07__18_12_35 turn 2, both cele should be able to grab the powerup.

**Comment by Zheneq** [comment]
One of them missed

![img](https://github.com/Zheneq/hc/assets/6827970/b143fcaa-1903-4d5c-932d-11cfd502dfb6)
Powerup square is not highlighted
