### ISSUE TITLE
Grey dash bug

### ISSUE THREAD

**Issue by Wantee-Rumisbind** [Zheneq/hc#62]
Server: Tethys-4
Build: 0.7.5.1
Game: 2024_01_19__20_45_16
Map: Oblivion 
Time: Approximately 21:45 CET
Round: 12

At round 12, I find myself at low hp and wanted to dash out to my drone setup on the other side of the map, but I could only a single location was highlighted as being dashable to. I sadly did not try to dash to the other possibles locations that weren't highlighted so I do not know if it is purely a visual bug. My drone was setup on top of an invisibility zone and I use the "Infrared Enhancements" ability on the drone to attack invisible enemies.

![image](https://github.com/Zheneq/hc/assets/157171659/a1c7ae97-81a9-40e2-b239-2101ba42c5c0)

Edit: I took the picture from replay
Edit 2: Just went into another match and the skill was working fine (different map)

**Comment by Sizzlefrost** [comment]
Could it be the range restriction? Grey dash is range-limited, separately from the drone. If part of the spots are in range, and others aren't, then you won't have every tile under the drone as a dash option.

**Comment by Wantee-Rumisbind** [comment]
there is a range limit ?  that might explain it ... I have never ever encountered it before and I loved playing Grey on the official servers XD

**Comment by Wantee-Rumisbind** [comment]
Okay, playing another match with Grey, got a visual bug. All the cells were working but no visual indicator. I was pretty close to my drone so it's not a range factor
Server: Tethys-3
Build: 0.7.5.1
Game: 2024_01_20__10_46_18
Map: Omni Reactor Core
Time: Approximately 12:06 CET
Round: 19
![image](https://github.com/Zheneq/hc/assets/157171659/3f9b2a2a-3213-47cf-b919-4273c3a71524)

**Comment by Zheneq** [comment]
The original issue is intended behaviour, and the other issue doesn't seem to be a server problem
